# Generated by Django 5.0 on 2023-12-10 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='quality_rating_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
