# Generated by Django 5.0 on 2023-12-10 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VendorApp', '0002_purchaseorder_quality_rating_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaseorder',
            name='quality_rating_submitted',
        ),
    ]
